### ISSUE TITLE
Avatars customized to rounded are not round

### ISSUE THREAD

**Issue by GeneralUltra758** [MythikAngel/miku-discord-theme#17]
When setting --avatar-radius: 50px; avatars are not fully round,
Example of non round pfp in DM and servers and size reporting as 40x50

![image](https://user-images.githubusercontent.com/13122460/80281208-e1bdf700-8709-11ea-9c31-0aeed31b38eb.png)

![image](https://user-images.githubusercontent.com/13122460/80281386-f949af80-870a-11ea-8030-e34fc3d5fa3f.png)

inspect element shows avatars are 40x50, removing padding-top 10px from
```css
.group-spacing-16 .groupStart-23k01U>div>img {
    padding-top: 10px;
}
```
 messes up the alignment but makes the avatar be 40x40 and round
